# This is the schema file for the OEFDB.
# It is a TOML file - for more information on the format, see here https://github.com/toml-lang/toml
# It currently contains a list of columns, and what data is valid for each column
# Lines starting with "#"'s are comments

# See the description of the first column for the structure of the column

# The [[columns]] denotes the start of a new column
# The columns are ordered - it is checked that the columns are in the same order in this file and in the CSV file
[[columns]]
# This is the name of the column - aka the name that is in the header row
name = "sector"
# This is the list of "validators" to apply to each value in the column. Each validator will validate some aspect of of the value
# All validators must pass for a value to be considered valid.
validators = ["is_allowed_string", "is_ascii"]
# Most validators expect that the CSV value is not-empty. If you want to allow *both* empty values, and values that pass
# all validators, set allow_empty to be true. Then empty values will always be considered valid
allow_empty = false

# Here another [[columns]] denotes the start of the next column, and so forth
[[columns]]
name = "category"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "activity_id"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "name"
validators = ["is_allowed_string"]
allow_empty = false

[[columns]]
name = "activity_unit"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "kgCO2e-AR5"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgCO2e-AR4"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgCO2"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgCH4"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgN2O"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgCO2e-OtherGHGs-AR5"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "kgCO2e-OtherGHGs-AR4"
validators = ["is_float_or_not_supplied"]
allow_empty = true

[[columns]]
name = "uncertainty"
validators = ["is_int"]
allow_empty = true

[[columns]]
name = "scope"
validators = []
allow_empty = true

[[columns]]
name = "lca_activity"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "source"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "year_released"
validators = ["is_year"]
allow_empty = false

[[columns]]
name = "years_valid"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = true

[[columns]]
name = "years_calculated_from"
validators = ["is_year"]
allow_empty = true

[[columns]]
name = "region"
validators = ["is_allowed_string", "is_ascii"]
allow_empty = false

[[columns]]
name = "data_quality"
validators = []
allow_empty = false

[[columns]]
name = "contributor"
validators = ["is_allowed_string"]
allow_empty = true

[[columns]]
name = "date_accessed"
validators = ["is_date"]
allow_empty = false

[[columns]]
name = "description"
validators = ["is_allowed_string"]
allow_empty = false

[[columns]]
name = "source_link"
validators = ["is_link"]
allow_empty = false
